[termination]
seconds_spent_limit = 2
[[phases]]
type = "construction_heuristic"
construction_heuristic_type = "first_fit"
[[phases]]
type = "local_search"
[phases.termination]
step_count_limit = 200
[phases.move_selector]
type = "change_move_selector"
